### ISSUE TITLE
仅处理上行且远程端口为80的TCP数据包

### ISSUE THREAD

**Issue by NullYing** [yzsme/CCDGUTNetCrackerR#1]
1.仅处理上行且远程端口为80的TCP数据包 - > udp数据无需处理？？？
2.能简单说一下他的多客户端检测机制是什么吗？

**Comment by gintoki1010** [comment]
padavan系统适合用哪个二进制文件？

**Comment by yzslab** [comment]
@NullYing 对的，UDP不处理，检测多客户端的，目前发现关键是UA。

**Comment by NullYing** [comment]
UA检测手机与电脑同时使用？

**Comment by yzslab** [comment]
@gintoki1010 一般可以直接使用mipsel-static，不过最好下载toolchain自己编译非static版本的。

**Comment by yzslab** [comment]
@NullYing 关键应该是手机的UA吧，因为手机多起来就会触发多客户端限制，但是多台桌面设备没事。

**Comment by NullYing** [comment]
实际测试过了吗？剔除UA之后可以多台手机？

**Comment by yzslab** [comment]
@NullYing 在我宿舍还有两个同学的宿舍测试了，暂时还没发现问题，期待更广泛的测试。

**Comment by gintoki1010** [comment]
@yzsme padavan看来是要自己重新编译了，iptables couldn't find match 'comment'。

**Comment by NullYing** [comment]
iptables版本的原因吧，删除comment参数试试

**Comment by NullYing** [comment]
@yzsme 测试完请务必告知结果，感谢

**Comment by yzslab** [comment]
@gintoki1010 打开main.c，查找:
`-m comment --comment \"CCDGUTNetCracker\"`
删掉，然后编译。

**Comment by NullYing** [comment]
@yzsme 测试有效吗？

**Comment by yzslab** [comment]
@NullYing 目前有效，使用的这两天没有收到共享网络的警告。

**Comment by CalenZhang** [comment]
怎么运行mipsel-static啊
