### ISSUE TITLE
该软件能否设置开机自启？

### ISSUE THREAD

**Issue by includemuke** [yzsme/CCDGUTNetCrackerR#2]
软件每次都是手动开启，觉得有点麻烦，想通过脚本设置一下开机自启，但是对这个不熟，照着网上的教程写的，代码如下：
```
#!/bin/sh/etc/rc.common
#/init.d/ziqi
START = 99
STOP = 20
start()
{
sleep 10 
/root/CCDGUTNetCrackerR& 
}
stop()
{
killall ziqi
}
```

路由器后台的启动项有显示此程序了，但是没有启动成功，我觉得应该是脚本写错了，但是无从下手，请问如何修改？
我的路由器固件是潘多拉1.61版本。

**Comment by yzslab** [comment]
打开文件：/etc/rc.local
在exit 0之前（如果没有则忽略），加入:
`
/root/CCDGUTNetCrackerR 私有网络接口名 daemon
`

**Comment by includemuke** [comment]
已解决，十分感谢。
