### ISSUE TITLE
关于v0.1.3版本使用的问题

### ISSUE THREAD

**Issue by includemuke** [yzsme/CCDGUTNetCrackerR#5]
下载的是CCDGUTNetCrackerR-mipsel-static.bz2
解压后拷贝文件到路由器的/ usr/sbin/CCDGUTNetCrackerR

并在/etc/rc.local中编写代码如下：
```
sed -i "/CCDGUTNetCrackerR/d" /etc/rc.local
cat /etc/rc.local | grep "exit 0"
sed -i "/exit 0/i/usr/sbin/CCDGUTNetCrackerR br-lan daemon" /etc/rc.local
echo /usr/sbin/CCDGUTNetCrackerR br-lan daemon >> /etc/rc.local
exit 0
```

但是使用过程中总是掉线，经常被强制注销，在putty中输入top指令也没有看到程序运行

于是我把文件移动到/root/CCDGUTNetCrackerR中，
并在/etc/rc.local中编写代码如下：
```
/root/CCDGUTNetCrackerR br-lan daemon
exit 0
```

结果还是经常被强制注销，导致断网，请问这是什么原因？

注：我使用第二种方法设置0.1.1版本自启时就没有问题

**Comment by yzslab** [comment]
如果是通过WinSCP之类的工具传到路由器里面的，请执行：
```
chmod +x /root/CCDGUTNetCrackerR
sync
```
然后重启路由器：
```
reboot
```
或者直接启动程序：
```
/root/CCDGUTNetCrackerR br-lan daemon
```

**Comment by includemuke** [comment]
好的，今晚试试，测试后再回复

**Comment by includemuke** [comment]
@yzsme 之前是在winscp界面里手动修改文件属性的，可能没刷新或没重启等之类问题导致不能自启，现已测试成功，十分感谢大佬的细心解答。
