### ISSUE TITLE
无法连接http等若干问题

### ISSUE THREAD

**Issue by RadarEcho** [yzsme/CCDGUTNetCrackerR#7]
问题一：
小米路由器青春版pandorabox固件 Base on LEDE/OpenWrt (18.08, 2018-08-25-git-d506c73d2)
```
[root@PandoraBox_6862:/root]#chmod +x /usr/sbin/CCDGUTNetCrackerR
[root@PandoraBox_6862:/root]#CCDGUTNetCrackerR br-lan daemon
Delete firewall rule.
Add firewall rule.
```
之后192.168.1.1路由器管理界面打不开，并且浏览器只能访问https页面

问题二：
小米路由器青春版LEDE固件 (17.01.1, r3316-7eb58cf109)
```
root@LEDE:~# chmod +x /usr/sbin/CCDGUTNetCrackerR
root@LEDE:~# CCDGUTNetCrackerR br-lan daemon
Illegal instruction
```
没有任何效果

请大佬帮助解决

**Comment by Ivaneus** [comment]
我用格尼相同的pandorabox固件没有这个问题一

**Comment by includemuke** [comment]
> 
> 
> 问题一：
> 小米路由器青春版 pandorabox 固件 Base on LEDE/OpenWrt (18.08, 2018-08-25-git-d506c73d2)
> 
> ```
> [root@PandoraBox_6862:/root]#chmod +x /usr/sbin/CCDGUTNetCrackerR
> [root@PandoraBox_6862:/root]#CCDGUTNetCrackerR br-lan daemon
> Delete firewall rule.
> Add firewall rule.
> ```
> 
> 之后 192.168.1.1 路由器管理界面打不开，并且浏览器只能访问 https 页面
> 
> 问题二：
> 小米路由器青春版 LEDE 固件 (17.01.1, r3316-7eb58cf109)
> 
> ```
> root@LEDE:~# chmod +x /usr/sbin/CCDGUTNetCrackerR
> root@LEDE:~# CCDGUTNetCrackerR br-lan daemon
> Illegal instruction
> ```
> 
> 没有任何效果
> 
> 请大佬帮助解决

小米路由器青春版是mips架构的。

**Comment by Ivaneus** [comment]
下载pandorabox sdk 在UB18.04环境下交叉编译插件，插件放到小米青春版即可

**Comment by Subdue0** [comment]
wgame，LOL下载器，steam下载之类的加速效果，被破解插件影响到了，整体表现出来的效果就是下载速度非常慢，你试试看，会不会有影响

**Comment by Ivaneus** [comment]
腾讯那些下载器下载会附带一份ua来验证，补丁清除了，自然也就没法进入那些下载线路

**Comment by Subdue0** [comment]
在不清除插件的情况下，有办法解决吗

**Comment by Ivaneus** [comment]
用命令中止补丁试试

**Comment by Subdue0** [comment]
不光是腾讯，很多下载器都是这样的，包括wgame，steam之类

**Comment by Ivaneus** [comment]
很正常……弊端嘛

**Comment by Subdue0** [comment]
嗯，这我明白，就是有没有可能通过改动源码消除这种弊端

**Comment by Ivaneus** [comment]
前提是你得看得懂源码

**Comment by Subdue0** [comment]
太底层了，看不懂，哈哈哈

**Comment by yzslab** [comment]
你好，

感谢反馈。

无法访问HTTP页面的请尝试使用最新版本。

影响到下载速度的，可以尝试使用兼容模式版本。
